{{ with .Values.config.proxy }}
{{- if or .username .password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifact-registry.fullname" $ }}-proxy-auth
  labels:
    {{- include "artifact-registry.labels" $ | nindent 4 }}
type: Opaque
data:
  username: {{ printf "%s" .username | b64enc }}
  password: {{ printf "%s" .password | b64enc }}
{{- end }}
{{- end }}
