{{ with .Values.config }}
{{ $name := (include "artifact-registry.aesKeySecretName" $) }}
{{- if and (not (and (not (.aes).key) (((.aes).secret).name))) (not (lookup "v1" "Secret" $.Release.Namespace $name)) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "artifact-registry.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ include "artifact-registry.aesKeySecretKeyName" $ }}: {{ default (randAlphaNum 32) (.aes).key | b64enc | quote }}
{{- end }}
{{- end }}
