apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifact-registry.fullname" . }}
  labels:
    {{- include "artifact-registry.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ (empty (.Values.config.tls).secretName) | ternary "http" "https" }}
      protocol: TCP
      name: {{ (empty (.Values.config.tls).secretName) | ternary "http" "https" }}
  selector:
    {{- include "artifact-registry.selectorLabels" . | nindent 4 }}
